### ISSUE TITLE
Error Decoding Response Body

### ISSUE THREAD

**Issue by MagicalWitchAshley** [NotNite/skindl#1]
Not entirely sure what this is or what the issue is caused by, but Moruke's skin causes skindl to fail:
![skindlerror](https://github.com/NotNite/skindl/assets/48668484/055dcce1-cd1a-481f-a6fc-868e7812a545)
Test case: https://gamebanana.com/mods/481891

**Comment by NotNite** [comment]
Can only reproduce on the first file (`moruke_omura_red_.zip`), which returns a broken response from the GameBanana API:

![image](https://github.com/NotNite/skindl/assets/44414597/b4e1ce90-124e-4bab-934a-0b360b5300ff)

The other download links (which contain ID `481891` instead of `481890`) work correctly, and properly contain the first file:

![image](https://github.com/NotNite/skindl/assets/44414597/1fc6abf4-549c-4e68-87fe-4f3f94ff67bf)

This is a GameBanana bug, nothing I can do to fix it. Select one of the other 1-Click Install buttons to download the mod.
